kind: Service
apiVersion: v1
metadata:
  name: nominatim-api
  namespace: business-service
  labels:
    app: nominatim-api
spec:
  ports:
  - port: 8080
    name: web
    protocol: TCP
  selector:
    app: nominatim-api
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nominatim-api-stripprefix
  namespace: business-service
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nominatim-api-web
  namespace: business-service
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`nominatim.computaceae-it.tech`) && PathPrefix(`/api/`)
    services:
    - name: nominatim-api
      port: 8080
    middlewares:
    - name: kube-system-ip-whitelist@kubernetescrd
    - name: nominatim-api-stripprefix
      namespace: business-service
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nominatim-api-web-tls
  namespace: business-service
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`nominatim.computaceae-it.tech`) && PathPrefix(`/api/`)
    services:
    - name: nominatim-api
      port: 8080
    middlewares:
    - name: kube-system-ip-whitelist@kubernetescrd
    - name: nominatim-api-stripprefix
      namespace: business-service
  tls:
    certResolver: le