kind: Service
apiVersion: v1
metadata:
  name: nominatim-ui
  namespace: business-service
  labels:
    app: nominatim-ui
spec:
  ports:
  - port: 8765
    name: web
    protocol: TCP
  selector:
    app: nominatim-ui
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nominatim-ui-web
  namespace: business-service
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`nominatim.computaceae-it.tech`)
    services:
    - name: nominatim-ui
      port: 8765
    middlewares:
    - name: kube-system-ip-whitelist@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nominatim-ui-web-tls
  namespace: business-service
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`nominatim.computaceae-it.tech`)
    services:
    - name: nominatim-ui
      port: 8765
    middlewares:
    - name: kube-system-ip-whitelist@kubernetescrd
  tls:
    certResolver: le