apiVersion: apps/v1
kind: Deployment
metadata:
  name: nominatim
  namespace: business-service
  labels:
    app: nominatim
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nominatim
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nominatim
        date: DATE_DEPLOYMENT
    spec:
      containers:
      - name: nominatim
        image: registry.computaceae-it.tech/cit-nominatim
        imagePullPolicy: Always
        command: ["sh"]
        args: ["/app/startapache.sh"]
        resources:
          requests:
            cpu: 100m
            memory: 15Mi
          limits:
            cpu: 300m
            memory: 50Mi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        startupProbe:
          initialDelaySeconds: 30
          failureThreshold: 3
          periodSeconds: 10
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 3
          httpGet:
            path: /
            port: 8080
            
